###
// *************************** LOGIN and TOKENS *******************
// Login with dg1095 password encrypted 1 time
# @name login
POST http://localhost:3000/login
Content-Type: application/json

{
    "userid": "dgarvin57@gmail.com",
    "password": "dg1095"
}

###
// Encrypt a password
# @name login
POST http://localhost:3000/login/encrypt-password?passes=1
Content-Type: application/json
{
    "username": "dgarvin57@gmail.com",
    "password": "dg1095"
}

###
// *************************** USERS *******************
// Get all users with page limits -- DONE --
GET http://localhost:3000/user?listPerPage=100&page=1

###
// Get all users with order and direction
GET http://localhost:3000/user/?orderBy=organizationName&orderDir=ASC
//Authorization: Bearer {{accessToken}}

###
// Find users by page search text
GET http://localhost:3000/user/find?searchText=gmail
//Authorization: Bearer {{accessToken}}

###
// Find users by field filters
GET http://localhost:3000/user/find?filter=active=true
//Authorization: Bearer {{accessToken}}

###
// Get one user by id -- DONE --
GET http://localhost:3000/user/3

###
// Delete one user by id -- DONE --
DELETE http://localhost:3000/user/101
//Authorization: Bearer {{accessToken}}

###
// Create user -- DONE --
POST http://localhost:3000/user
Content-Type: application/json

{
    "userId": "tonyblack@successinc.com",
    "password": "password1234",
    "firstName": "Tony",
    "lastName": "Black",
    "phoneNumber": "201-399-2222",
    "organizationName": "Success, Inc.",
    "dateEnrolled": "2021-04-25"
}

###
// Update user -- DONE --
PUT http://localhost:3000/user/98
Content-Type: application/json

{
    "userId": "tonyblack@successinc.com",
    "password": "password1234",
    "firstName": "Anthony",
    "lastName": "Green",
    "phoneNumber": "202-333-4444",
    "organizationName": "Success, Inc.",
    "dateEnrolled": "2021-04-26"
}
