@domain=http://localhost:3000
//@domain=https://stress-immunity-reboot-api.herokuapp.com
###
// *************************** LOGIN and TOKENS *******************
// Login with dg1095 password encrypted 1 time
# @name login
POST {{domain}}/login
Content-Type: application/json

{
    "userid": "dgarvin57@gmail.com",
    "password": "dg1095"
}

###
// Encrypt a password
# @name login
POST {{domain}}/login/encrypt-password?passes=1
Content-Type: application/json
{
    "username": "dgarvin57@gmail.com",
    "password": "dg1095"
}

###
// *************************** USERS *******************
// Get all users with page limits
GET {{domain}}/user?listPerPage=10&page=2

###
// Get all users with ORDER and DIRECTION
GET {{domain}}/user/?orderBy=userId&orderDir=ASC
//Authorization: Bearer {{accessToken}}

###
// Find users by SEARCH TEXT
GET {{domain}}/user/find?searchText=@mac
//Authorization: Bearer {{accessToken}}

###
// Find users by FIELD FILTERS (and optionally combine with search text
GET {{domain}}/user/find?searchText=dan
Content-Type: application/json

{
    "organizationName": ["LIKE", "success"],
    "userId": ["LIKE", "@gm"],
    "active": ["=", "1"]
}

###
// Get one user by id
GET {{domain}}/user/3

###
// Delete one user by id
DELETE {{domain}}/user/162
//Authorization: Bearer {{accessToken}}

###
// Create user
POST {{domain}}/user
Content-Type: application/json

{
    "userId": "tonyblack@successinc.com",
    "password": "password1234",
    "firstName": "Tony",
    "lastName": "Black",
    "phoneNumber": "201-399-2222",
    "organizationName": "Success, Inc.",
    "dateEnrolled": "2021-04-25"
}

###
// Update user
PUT {{domain}}/user/163
Content-Type: application/json

{
    "userId": "briangreen@successinc.com",
    "password": "password1234",
    "firstName": "Brian",
    "lastName": "Green",
    "phoneNumber": "202-333-5345",
    "organizationName": "Success, Inc.",
    "dateEnrolled": "2021-04-24 00:00:00"
}
