@domain=http://localhost:3000
//@domain=https://stress-immunity-reboot-api.herokuapp.com
###
// *************************** LOGIN and TOKENS *******************
// Login with dg1095 password encrypted 1 time
# @name login
POST {{domain}}/login
Content-Type: application/json

{
    "userid": "dgarvin57@gmail.com",
    "password": "dg1095"
}

###
// Encrypt a password
# @name login
POST {{domain}}/login/encrypt-password?passes=1
Content-Type: application/json
{
    "username": "dgarvin57@gmail.com",
    "password": "dg1095"
}

###
// *************************** USERS *******************
// Get all users with page limits
GET {{domain}}/user?listPerPage=10&page=2

###
// Get all users with ORDER and DIRECTION
GET {{domain}}/user/?orderBy=userId&orderDir=ASC
//Authorization: Bearer {{accessToken}}

###
// Find users by SEARCH TEXT
GET {{domain}}/user/find?searchText=@mac
//Authorization: Bearer {{accessToken}}

###
// Find users by FIELD FILTERS (and optionally combine with search text
GET {{domain}}/user/find?searchText=dan
Content-Type: application/json

{
    "organizationName": ["LIKE", "success"],
    "userId": ["LIKE", "@gm"],
    "active": ["=", "1"]
}

###
// Get one user by id
GET {{domain}}/user/3

###
// Delete one user by id
DELETE {{domain}}/user/176
//Authorization: Bearer {{accessToken}}

###
// Create user
POST {{domain}}/user
Content-Type: application/json

{
    "userId": "bethevans@acme.com",
    "password": "passwor3323ss334",
    "firstName": "Beth",
    "lastName": "Evans",
    "phoneNumber": "232-999-8888",
    "organizationName": "Acme Chemical",
    "dateEnrolled": "2021-04-26"
}

###
// Update user
PUT {{domain}}/user/182
Content-Type: application/json

{
    "userId": "bethevans@acme.com",
    "password": "passwor3323ss334",
    "firstName": "Beth",
    "lastName": "Evans",
    "phoneNumber": "232-999-8887",
    "organizationName": "Acme Chemical",
    "dateEnrolled": "2021-04-26"
}
